[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn spotify_manager.wsgi"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"

[[cron]]
schedule = "0 9 * * *"
command = "python manage.py send_expiry_notifications"
timezone = "Asia/Tehran"
