# Generated by Django 5.1.5 on 2025-01-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyaccount',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AddIndex(
            model_name='spotifyaccount',
            index=models.Index(fields=['email'], name='accounts_sp_email_7772ae_idx'),
        ),
    ]
